version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - hy-network

  api-server:
    image: ${DOCKER_USERNAME}/api-server:latest
    container_name: api-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - redis
    networks:
      - hy-network
    restart: unless-stopped

  file-parser:
    image: ${DOCKER_USERNAME}/file-parser:latest
    container_name: file-parser
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
    ports:
      - "8081:8081"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - hy-network
    restart: unless-stopped

  admin-server:
    image: ${DOCKER_USERNAME}/admin-server:latest
    container_name: admin-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
      TZ: Asia/Seoul
    ports:
      - "8000:8000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - hy-network
    restart: unless-stopped

networks:
  hy-network:
    driver: bridge