version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - hy-network

  gateway-api:
    image: ${DOCKER_USERNAME}/gateway-api:latest
    container_name: gateway-api
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - hy-network
    restart: unless-stopped

  data-ingestor:
    image: ${DOCKER_USERNAME}/data-ingestor:latest
    container_name: data-ingestor
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    networks:
      - hy-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  hy-network:
    driver: bridge