name: CI

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]
    
jobs:
  build:
    #빌드 환경은 ubuntu 최신 버전으로
    runs-on: ubuntu-latest

    steps:
    #CI 서버에 체크아웃
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        #Amazon Corretto 배포본 사용
        distribution: 'corretto'
    
    - name: gradle set up
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: gradlew 권한 설정
      run: chmod +x gradlew

    - name: 빌드 확인
      run: ./gradlew build





